### ISSUE TITLE
Fix showable - they has to much controll over nodes

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#1]
When ShowableManager is used by showable nodes,
it locks their visibility and alternative methods of showing nodes doesn't work with it.
It shouldn't work that way, it made it harder to mix Rakugo with other code

**Comment by Jeremi360** [comment]
I thought we already talk about it @theludovyc, but just in case, I will write it here anyway.
We remove ShowableManager from Rakugo core totally.
And I will write something similar to ShowableManager as a separated addon, that will be more flexible and easier to use.

**Comment by Jeremi360** [comment]
`show` and `hide` will be part of nvkit RakuScript extension, 
and **ShowableManager** has been already removed, so we can close this.
