### ISSUE TITLE
No need for 2 Readme files

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-Dialogue-System#128]
This repo has now 2 Readme files:
- one at the root (`/`), that is been keep up-to-date
- second at *addons/Rakugo*, that is old and broken - this one we should remove

**Comment by theludovyc** [comment]
I think same this morning when I do pre release 1.0. I copy Readme and license from root into addon/Rakugo :)

Ok, remove readme and license from addon/Rakugo :)
