### ISSUE TITLE
New menu()

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#13]
**Old**
```menu(choices:Array, parameters:Dictionary)```
choices["choice label", variable_to_return:Variant, parameters:Dictionary]

**New**
```menu(choices:PoolStringArray)```
choices["text", "text1", "text2", ...]

**Use**
var ret_menu = menu(...)
match ret_menu

**Comment by Jeremi360** [comment]
Didn't you make a mistake?
You, wrote `menu(choices:PoolStringArray)`, but after that you write this `choices["text":str , "text1":str, ...]`,
 `key:value` only possible when you use Dictionary, but you wrote it using this brackets `[]` instead of `{}` ??

**Comment by theludovyc** [comment]
Corrected 👍 
Yeah my mistake, sorry ^^'

**Comment by Jeremi360** [comment]
@theludovyc So you want to use PoolStringArray for choices, instead of Dictionary.
I know I said the other way last time, but now I see one big problem with using indexes instead of keys:
What about making some choices not available if, for example, player don't have enough relationship points with npc.
Yes, user can alter array before passing it into `menu()`, but when he/she do that then `match` part of code after removed choice stop works as it should. 
Example:
```gdscript
var choices := ["Talk to Emily.", "Go with Emily to Arcade.", "Nothing"]
if Rakugo.get_var("emily.relationship") < 30:
  choices.remove(1)
 var choice := menu(choices)
 match:
   1: # "Talk to Emily"
      ...
    2 # "Go with Emily to Arcade", but when emily.relationship < 30 then this is called when press "Nothing":
      ...
    3 #  "Nothing" but when emily.relationship < 30 then this when it can give error:
      ...
```

**Comment by Jeremi360** [comment]
@theludovyc Using indexes also makes harder to add new choice between existing onces.

**Comment by theludovyc** [comment]
I have one question to help me think about it. Can we change the order of the choices?

**Comment by theludovyc** [comment]
I found this https://stackoverflow.com/questions/372915/game-logic-in-xml-files but I dislike to write choice label twice :/

**Comment by theludovyc** [comment]
Another possibility

var choices := {"tag":"label", ...}

and use tag in match

**Comment by Jeremi360** [comment]
Sorry, but GitHub only notify me if you address user using `@` ex. @theludovyc.

> I have one question to help me think about it. Can we change the order of the choices?

I think we can if we use Dictionaries then it is implemented out of the box, but I'm not sure what can be a use scenario for that.

> ... I dislike to write choice label twice :/

Also think this is not a good idea.

> Another possibility
> 
> var choices := {"tag":"label", ...}
> 
> and use tag in match

Yes, I think that this solution will be good enough.

**Comment by Jeremi360** [comment]
I think we can close this issue as we agreed to this menu:

```python
var choices := {"talk":"Talk to Emily.", "arcade":"Go with Emily to Arcade.", "leave":"Leave Emily."}

if Rakugo.get_var("emily.relationship") < 30:
  choices.remove("arcade")

var choice := menu(choices)
match:
  "talk": # "Talk to Emily"
    ...
  "arcade": # "Go with Emily to Arcade"
    ...
  "leave": # "Leave Emily"
    ...
 ```

**Comment by theludovyc** [comment]
Good to me :)
