### ISSUE TITLE
Remove AutoTimer and SkipTimer from Rakugo.tscn

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#141]
Currently in Rakugo.tscn
Rakugo, node
History, node
AutoTimer, timer
SkipTimer, timer

It is not Rakugo to handle AutoTimer and SkipTimer

**Comment by Jeremi360** [comment]
Yes remove them, they should be a paty of Kit

**Comment by theludovyc** [comment]
fix by #150
