### ISSUE TITLE
Rakugo, remove signal "ask_return" and "menu_return"

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#155]
After reflexion is bad architecture to use signal to restart parser thread.

Call directly current_parser.current_semaphore.post(), like in do_step() func.

**Comment by Jeremi360** [comment]
> After reflexion is bad architecture to use signal to restart parser thread.
Call directly current_parser.current_semaphore.post(), like in do_step() func.

@theludovyc 
1. why this is a bad  architecture ?
2. how I will pass answer from ask and choice in menu from ui to Rakugo then ?

**Comment by theludovyc** [comment]
"how I will pass answer from ask and choice in menu from ui to Rakugo then ?" not affected don't worry. It is about signals not methods.

I need to made screenshot to answer first one. Be patient :)

**Comment by Jeremi360** [comment]
> "how I will pass answer from ask and choice in menu from ui to Rakugo then ?" 
*not affected don't worry. It is about signals not methods.*

@theludovyc but titled this issuie *Rakugo, **remove signal** "ask_return" and "menu_return"*.
So will you removing them or not ?

**Comment by theludovyc** [comment]
Yes, we no talk about same signals. Look...

When "say" is read in an rk script it call Rakugo.say and then stop thread.
To restart it, you need to call Rakugo.do_step() somewhere in your code.
```gd
func do_step():
  waiting_step = false

  current_parser.current_semaphore.post()
```

When "ask" is read it call Rakugo.ask and then stop thread.
To restart it, you need to call Rakugo.ask_return()
```gd
func ask_return(result):
  waiting_ask_return = false

  set_variable(variable_ask_name, result)
  
  Rakugo.emit_signal("ask_return", result)
```

**Difference is in do_step() we use parser directly to post(), instead in ask_return() we send a signal.**

This signal is connected in the _init() of Parser class and call this function
```gd
func _on_ask_return(result):
  current_semaphore.post()
```

Same result, but different way. So, we need to refactor it, and removed useless signal. Plus users should never use it.
