### ISSUE TITLE
StoreManager, save folder path is not updated from rakugo parameters

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#168]
Currently save folder is set in _ready func (plus setting path is wrong)
```gd
func _ready():
  save_folder_path = ProjectSettings.get_setting("rakugo/save_folder")
```

But StoreManager is not instancied in a scene like a node, so _ready is never executed.

Should replaced by _init
```gd
func _init():
  save_folder_path = ProjectSettings.get_setting("addons/rakugo/save_folder")
```

In same time, clean StoreManager and remove `var save_folder_path = "user://saves"`.

**Comment by Jeremi360** [comment]
Yes, you are right we need to changed it.

**Comment by theludovyc** [comment]
Just need to copy code from StoreManager in #164 (Except parsed_scripts and load_rk)
