### ISSUE TITLE
Plugin.gd, update setting "addons/rakugo/save_folder" to "user://saves"

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#169]
Currently settings is "res://saves". This is bad, users have this settings by default. Saves should be created in "user://saves"

**Comment by Jeremi360** [comment]
This was so it will be easier to test/check saves, but now when everything works it can be back to "user://saves"

**Comment by theludovyc** [comment]
We can change this setting in this repo, to test/check saves easier.

The problem is that by default it is "res://saves". So when user download a release and enable plugin, it save in res:// and not in user://. And that is bad.

**Comment by Jeremi360** [comment]
@theludovyc 
Apparently I have not made myself clear,
You are right that this may be a problem and we will change it.
But not by changing in ProjectSettings but in plugin.gd, because there it is initialization

**Comment by theludovyc** [comment]
I have doubt sorry. Glad it is clear now :) !
