### ISSUE TITLE
Rakugo do not need to handle parameters for GUI

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#17]
Issues linked #13 #14 #15 #16

**Comment by Jeremi360** [comment]
To kits I will add funcs like `set_style_menu()` and `add_timer_to_menu()` for handling this if needed.

**Comment by Jeremi360** [comment]
I think we can close this issue.
Only adding one note that we will use (for ex.) `kit.set_parameters({"time_typing":0.5})` instead, func per parameter ⬆️ for this.
