### ISSUE TITLE
Gut, One test class to rule them all

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#174]
If you look in https://github.com/rakugoteam/Rakugo/blob/main/Test/TestParser/TestAsk/TestAsk.gd, https://github.com/rakugoteam/Rakugo/blob/main/Test/TestParser/TestSay/TestSay.gd, and futur updated tests. You can see lot of similar code.

Like file_base_name, parse_and_execute follow by yield, yield follow by assert_signal, assert_true before do_step, etc...

I propose to mutualize them in a class than extends GutTest, call RakugoTest. I thinked about an autoload script, but for me it looks like less good.

What do you think about it ?

**Comment by Jeremi360** [comment]
It sound like a good idea :+1:
