### ISSUE TITLE
Add signal to `exit` keyword

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-Dialogue-System#182]
@theludovyc 
I propose to add signal `on_exit` that will be called when `exit` keyword is executed.
It would be useful for example:
- to hide dialogue UI when characters end dialogue, so player can go to more interactive part of gameplay
- switch to different godot scene
- open some custom UI with mingame

**Comment by theludovyc** [comment]
When you exit, execute_script() ends and signal "execute_script_finished" is emitted. Is not enough ?

**Comment by Jeremi360** [comment]
> When you exit, execute_script() ends and signal "execute_script_finished" is emitted. Is not enough ?

Sorry @theludovyc , I didn't remember that, I close it issue then.
