### ISSUE TITLE
Tests, move tests wich concerns Exectuer in TestExecuter folder

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#184]
As Parser has been divided in Parser and Executer, numbers of tests in TestParser can be moved in TestExecuter folder (and we can create it). To make things proper :) !

**Comment by Jeremi360** [comment]
> As Parser has been divided in Parser and Executer, numbers of tests in TestParser can be moved in TestExecuter folder (and we can create it). To make things proper :) !

I like keeping stuff organized @theludovyc 😄

**Comment by Jeremi360** [comment]
It been done already co we can close this.
