### ISSUE TITLE
Rakugo, get_character_variable push same error two times

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#188]
get_character_variable call get_character that push an error if a character as not found. But first one do it too. So same error are pushed two times.

**Comment by Jeremi360** [comment]
Then it should use `has_character()` before trying to use `get_character()`

**Comment by theludovyc** [comment]
It is more simple if we remove second one

![image](https://user-images.githubusercontent.com/7337158/213421099-124946b9-6052-4d53-85be-9e42925e9963.png)

You should not call has_character before get_character, it is useless.
has_character is only for check if you have one
get_character is to get it. if it not exist it return null. so it already handle "has_character"

**Comment by Jeremi360** [comment]
I see, you are right, I forgot that `get_character()` already pushes the error 
and that we return available variables in error if character exist, 
so just removing second one push error will be easier.
