### ISSUE TITLE
Rakugo, get_character call deprecated character_exists

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#189]
Like title say

**Comment by Jeremi360** [comment]
@theludovyc  I already made #170 , I wanted yo just remove `character_exists` is next version.
So what this is for then ?

**Comment by theludovyc** [comment]
> So what this is for then ?

To not forget. And we can do it already. So then we just need to remove character_exists. Plus it not push an error when user call get_character.

**Comment by Jeremi360** [comment]
> To not forget. And we can do it already. So then we just need to remove character_exists. Plus it not push an error when user call get_character.

Okay I see, I misinterpreted the title then, I thought you want to combine `get_character` and  `has_character`/`character_exist` into one func, sorry.

**Comment by theludovyc** [comment]
Okay, I see, do not worry :)
