### ISSUE TITLE
Rakugo, rename in "Rakugo Dialogue System"

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#197]
We use often Rakugo(Core) to talk about this project.

Rename it can allow to talk about Rakugo as global project. It fit with Rakugo team.

**Comment by Jeremi360** [comment]
> We use often Rakugo(Core) to talk about this project.

> Rename it can allow to talk about Rakugo as global project. It fit with Rakugo team.

You mean repo and addon ?

**Comment by theludovyc** [comment]
I mean just this repo :) !

**Comment by Jeremi360** [comment]
> I mean just this repo :) !

I can, but it will give as wired looking url to repo :/
![image](https://user-images.githubusercontent.com/1294815/218513441-3c379454-5489-42bd-a75d-a7b1673bdb47.png)

So maybe `Rakugo.Core` ?

**Comment by Jeremi360** [comment]
@theludovyc :arrow_up:  ?

**Comment by theludovyc** [comment]
Maybe "RakugoCore" for repo url, and Rakugo(Core) on readme ?

Or we can rename it as it is "DialogSystem" ? What do you think about it ?
It give repo url "rakugoteam/DialogSystem"

**Comment by Jeremi360** [comment]
> "rakugoteam/DialogSystem"

I think it can be the best solucion it shows out of the box what this repo is all about, 
but then should we change, also name of addon ?

**Comment by theludovyc** [comment]
Oh yeah !
And the name of folder for the plugin can be "RakugoDialogSystem", so people can see Rakugo and not just DialogSystem ?

**Comment by Jeremi360** [comment]
> And the name of folder for the plugin can be "RakugoDialogSystem", so people can see Rakugo and not just DialogSystem ?

Heya that is a grate idea, we will need to make for user instruction how to ~easy~ update paths, ~or script that will do that~.

**Comment by Jeremi360** [comment]
- [ ] rename *addons/Rakugo* to *addons/rakugo-dialogue-system*
   (from what I see for all addons in godot is accepted to write their names in this way and rest of our addons follow this)
- [ ] rename repo to *Rakugo Dialogue System*
- [ ] update links in *README*s in our repos
- [ ] update links at our web pages
