### ISSUE TITLE
Executer, rename sg_parser_unhandled_regex

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#203]
Since Parser was split in two, it is Executer send this signal.

So I think we can rename it in "sg_custom_regex" ?

**Comment by Jeremi360** [comment]
> Since Parser was split in two, it is Executer send this signal.
>
> So I think we can rename it in "sg_custom_regex" ?

Yes, I think this is a good name and previous name felt me as being too long.
And I think we should name function that adds regex `add_custom_regex()` then.

**Comment by theludovyc** [comment]
Also agree for add_custom_regex()

**Comment by theludovyc** [comment]
Maybe `add_custom_regex_to_parse(...)` is better ?

**Comment by Jeremi360** [comment]
> Maybe `add_custom_regex_to_parse(...)` is better ?

@theludovyc this is really long name for func, and I don't like it.
And to make this clear we can just comments so it automatically clearly it out in docs.
On the other hand your in proposition is func name self explanatory.

**Comment by theludovyc** [comment]
I am afraid that `add_custom_regex()` is too ambiguous. But yes with comments it can be good :)

**Comment by Jeremi360** [comment]
> I am afraid that `add_custom_regex()` is too ambiguous. But yes with comments it can be good :)

I think it would be  ambiguous only if we had some other func with similar name or functionality

**Comment by theludovyc** [comment]
I see what you mean. So let's go for `add_custom_regex()` :)
