### ISSUE TITLE
Update GUT Test to work with last Rakugo verison

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-Dialogue-System#213]
GUT Tests doesn't work now as they use old signal names and old funcs names.

**Comment by Jeremi360** [comment]
I fixed all of our test, but it seam that they are bugs in GUT itself that make impossible to run all tests at one 
I will check if there is new version available and if so will update version in our repo.
Alternatively I can add plug-gd with config for GUT repo so we can easy update GUT, 
but have `addons/GUT` in gitignore.
@theludovyc what do you think ?

**Comment by theludovyc** [comment]
Hello @Jeremi360 :) !

> I fixed all of our test, but it seam that they are bugs in GUT itself that make impossible to run all tests at one

I haved same, but they all works one by one.

> Alternatively I can add plug-gd with config for GUT

No, beacause you cannot know if it will work with others versions, and/or if you have something deprecated. That's why I choose to copy gut directly. It is also the reason I do not want to use plug-gd on vnkit.

**Comment by Jeremi360** [comment]
@theludovyc 
> I haved same, but they all works one by one.

I see, but there is all of them. But okey I will try them one by one before making PR for this.

> No, beacause you cannot know if it will work with others versions, and/or if you have something deprecated. That's why I choose to copy gut directly. It is also the reason I do not want to use plug-gd on vnkit.

Okey then I will don't update it.
I think having to update manually is pain and can make repo big and mess if you have a lot of them.
In plug-gd you can setup it to use given repo, version or even commit no problem (examples from official [readme](https://github.com/imjp94/gd-plug#more-examples)):
```gdscript
  plug("imjp94/UIDesignTool", {"branch": "demo"}) # Always pull update from "demo" branch
  plug("imjp94/gd-YAFSM", {"tag": "1.0.0-stable"}) # Freeze to stable version
  plug("imjp94/gd-plug", {"commit": "7a642f90d3fb88976dd913051de994e58e838d1a"})
```

**Comment by theludovyc** [comment]
> I see, but there is all of them. But okey I will try them one by one before making PR for this.

You can run them all, and rerun those fail one by one :)

> I think having to update manually is pain and can make repo big and mess if you have a lot of them.

Yeah, I know it is easy to use plug-gd. Little annoying to update by hand. But it add instability and we lost control on the project, I think. Without it, you will be sure all of developper have same environment. And you just need to clone the repo.

**Comment by Jeremi360** [comment]
> But it add instability and we lost control on the project, I think. 

I don't see way you think this way.

> Without it, you will be sure all of developer have same environment. And you just need to clone the repo.

So about that for me is more clear when I use plug-gd as when I had manual copies of addons I often forget to update them. Also it allows me to had other addons in gitignore so I wouldn't fix something only in this copy instead of right repo clone. I don't like to have other code in repo that project code itself.
I wanted to make our repos easy to clone, but I discover fast that you can't use sub dirs with git submodules this is way I use plug-gd.

**Comment by Jeremi360** [comment]
@theludovyc Now it passes all tests except one `TestStartFormLabel`:
![image](https://user-images.githubusercontent.com/1294815/234325395-97ea5787-d217-4fdf-962d-b94be810b143.png)
 Any Ideas way ?

**Comment by theludovyc** [comment]
> GUT Tests doesn't work now as they use old signal names and old funcs names.
> I fixed all of our test, but it seam that they are bugs in GUT itself that make impossible to run all tests at one

I do not see your PR with these updates :)

**Comment by Jeremi360** [comment]
> I do not see your PR with these updates :)

@theludovyc My bad see #215
