### ISSUE TITLE
Parser, line number in error should start from 1 instead of 0

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-Dialogue-System#219]
Now when error or warning is reported there are 2 problems with it:
1. it starts count from 0 and should from 1
2. when line ends with tab then it see it this tab as start of new line

I base on this @theludovyc discord message:
![image](https://user-images.githubusercontent.com/1294815/236380060-3cfffbc0-f288-4124-90ff-3fc9ed81848b.png)
https://discord.com/channels/484604562183815169/484605786752942090/1103741738645995551

**Comment by theludovyc** [comment]
The line number is not same because is not the same error. As you can see
![image](https://user-images.githubusercontent.com/7337158/236417877-c7309849-bcbf-4cf1-b845-7fa88602ff54.png)

But we are agree line number should start from 1 and not 0. Professional deformation :p

**Comment by Jeremi360** [comment]
> The line number is not same because is not the same error.

I see @theludovyc , I will misunderstand your message.
This means that fix this we need only only to increase number in `push_warning()` 
and do not move the rest of the code.

**Comment by theludovyc** [comment]
> This means that fix this we need only only to increase number in push_warning()
and do not move the rest of the code.

Exactly 😊
