### ISSUE TITLE
Parser, do not check indent for choices

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#220]
Choices are the only things that the parser check the indent level to go out from menu state.

if we remove it, the user can indent his code like he want.

**Comment by Jeremi360** [comment]
If you remove need for them then how user will end menu block ?

**Comment by theludovyc** [comment]
With every new line that is not a choice, like empty line, comment, other rkscript instructions, or end of file

**Comment by Jeremi360** [comment]
I see this is good idea @theludovyc

**Comment by theludovyc** [comment]
Yeah sometimes it happen 😂
