### ISSUE TITLE
Fix Ask, is not correspond to the doc

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#245]
In the doc
`[var_name] = ? [character_tag] [question] [placeholder]`

In rakugo
`[var_name] = [character_tag] [question] ? [placeholder]`

The doc version is better.

Plus the current ask regex
`"^(?<variable>{VARIABLE}) = ((?<character_tag>{NAME}) )?(?<question>{STRING}) \\? (?<default_answer>{STRING})$"`

Force the user to add a space at the end after the '?', if you do not want to add default answer

**Comment by Jeremi360** [comment]
@theludovyc 
I also think that doc version is better - it easier to find/see where you have asks in script.
