### ISSUE TITLE
Executer, Variables in string are only replaced in SAY

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#255]
When you put a variable in ask like "How old are you <gd.name> ?"

The variable is not replaced. It is only works for SAY.

**Comment by Jeremi360** [comment]
> When you put a variable in ask like "How old are you <gd.name> ?"
The variable is not replaced. It is only works for SAY.

We must fix it, I think we could miss it because the Visual Novel Kit used a parser, which also had such functionality for variables and this meant that this error was not seen before.

**Comment by Jeremi360** [comment]
> When you put a variable in ask like "How old are you <gd.name> ?"
The variable is not replaced. It is only works for SAY.

@theludovyc 
You checked only `ask` ? We also need this to work in menu choices.

We must fix it, I think we could miss it because the Visual Novel Kit used a parser, which also had such functionality for variables and this meant that this error was not seen before.

**Comment by theludovyc** [comment]
> You checked only ask ? We also need this to work in menu choices.

On all strings :)

**Comment by Jeremi360** [comment]
I'm working on it, @theludovyc , but I see that you make parsing strings for `say` in *Executer.gd* and not in *Parser.gd* can I know way ?

**Comment by theludovyc** [comment]
What do you want to mean by that ? 😊

**Comment by Jeremi360** [comment]
> What do you want to mean by that ? 😊

@theludovyc I'm just curious way this is done in Executer.gd and not in Parser.gd.

But it dones't matter as I done this in #256 , I need just to test it - I will do it soon.
And maybe you can give better name for funcion I just than `do_variables()`

**Comment by theludovyc** [comment]
I not get it what you mean by parse string in executer and not in parser ?

You can name it: replace_variables()

**Comment by Jeremi360** [comment]
> I not get it what you mean by parse string in executer and not in parser ?

@theludovyc never mind, I already understood why it must be done in Executer.gd and not in Parser.gd

> You can name it: replace_variables()

Yes this is good idea.

**Comment by Jeremi360** [comment]
@theludovyc Unit Test I made for Variables in String gvies me pass for every one test :grin:  :
![image](https://github.com/rakugoteam/Rakugo-Dialogue-System/assets/1294815/dc9d62cf-f65f-4f73-a383-6510281e6b76)

But is this a good test ? I don't have much experience with those so I'm not sure:
https://github.com/Jeremi360/Rakugo/blob/do_variables/Test/TestExecuter/TestVarsInStrings/TestVarsInStrings.gd

**Comment by theludovyc** [comment]
Yes good, but at wrong places. You do not need to recreate one. Add them in TestSay, testMenu and testAsk. And you should verify the test end properly, with wait_execute_script_finished 😊

**Comment by Jeremi360** [comment]
> Yes good, but at wrong places. You do not need to recreate one. Add them in TestSay, testMenu and testAsk. And you should verify the test end properly, with wait_execute_script_finished 😊

@theludovyc So I put it in *TestExecuter* as `replace_variables()` is done in *Executer.gd*.
I had `wait_execute_script_finished()` but this was only one test it was faling, so I removed it: https://github.com/rakugoteam/Rakugo-Dialogue-System/pull/256/commits/462d1fe26ab99b981cebb4ab928f5dab5cf2d48f

**Comment by Jeremi360** [comment]
> You should verify the test end properly, with wait_execute_script_finished 😊

@theludovyc
I made one test do it simpler to test this one feature, and make me sure that I understat how to use GUT as it new for me.

I added `assert_menu_return(0)` before `wait_execute_script_finished()` and now it passes all checks :sunglasses: 

![image](https://github.com/rakugoteam/Rakugo-Dialogue-System/assets/1294815/0dc66e53-c6aa-4d2e-b20b-e1257672d7d1)

**Comment by Jeremi360** [comment]
@theludovyc How your `TestSay.test_say_variable()` should work at all if you don't crate and check what is variable in the first place ?

https://github.com/rakugoteam/Rakugo-Dialogue-System/blob/9a7efde8b8cb339fa914ab835f3c14728a686397/Test/TestParser/TestSay/TestSay.gd#L54-L73

**Comment by Jeremi360** [comment]
> Yes good, but at wrong places. You do not need to recreate one. Add them in TestSay, testMenu and testAsk.

@theludovyc 
No, no, no there is no sense in testing it using *Paser.gd* as `replace_variables()` is done by *Executer.gd* as it need to be done at run time so it reacts to changes in variables. If it was done by *Paser.gd* then value of variable in string would be the same:
```renpy
a = 2
"a is <a>" # -> a is 2
a = 4
"a is <a>" # -> a is 2 # it wouldn't react to change in line above
```
Also there is already test `TestSay.test_say_variable()` made by you, but it doesn't make any sense as it dosen't define variable or checks it value in say string it self:
https://github.com/rakugoteam/Rakugo-Dialogue-System/blob/9a7efde8b8cb339fa914ab835f3c14728a686397/Test/TestParser/TestSay/TestSay.gd#L54-L73

**Comment by theludovyc** [comment]
When we split parser and executer we start to split tests too. But the job is not finished yet and you have test in Parser folder that parse and execute. But you have some tests in Execute folder. And if I am not wrong we have one for Say and Ask, maybe not Menu. You can update them to make them better. You do not need to create variable from an rkscript you can use Rakugo.set_variable if needed.

**Comment by Jeremi360** [comment]
@theludovyc never mind, Okay my bad, there are TestSay, testMenu and testAsk in *TestExecuter*.
Now I will move tests from *TestVarsInStrings.gd* to proper test in *TestExecuter*, sorry for the confusion.

**Comment by Jeremi360** [comment]
@theludovyc I see why I made this mistake and was so confused, by mistakie you connected TestParser scripts to TestExcute scenes:

https://github.com/rakugoteam/Rakugo-Dialogue-System/blob/9a7efde8b8cb339fa914ab835f3c14728a686397/Test/TestExecuter/TestAsk/TestAsk.tscn#L3

https://github.com/rakugoteam/Rakugo-Dialogue-System/blob/9a7efde8b8cb339fa914ab835f3c14728a686397/Test/TestExecuter/TestMenu/TestMenu.tscn#L3

https://github.com/rakugoteam/Rakugo-Dialogue-System/blob/9a7efde8b8cb339fa914ab835f3c14728a686397/Test/TestExecuter/TestSay/TestSay.tscn#L3

I will fix that!

**Comment by Jeremi360** [comment]
@theludovyc I fixed this and moved all test from *TestVarsInStrings.gd* to proper test in TestExecuter, but I need to fix one thing `a = "a<b>"` works in script, but not in `Rakugo.set_variable()` or `Rakugo.set_character_variable()` but it easy to fix.

**Comment by theludovyc** [comment]
Woups... Sorry about that, I never saw it because of gut. Maybe the scene is not needed ? Thank you to handle it 😊

**Comment by Jeremi360** [comment]
@theludovyc Its almost works, but our variables are not dynamic :/
![image](https://github.com/rakugoteam/Rakugo-Dialogue-System/assets/1294815/36670491-bab0-4f5d-83bc-fc2f31101586)

**Comment by Jeremi360** [comment]
@theludovyc Now it works and pass all test and I added test for dynamic use `<var>` in side other variable string:
```
test_var = "a"
test_var_b = "<test_var>b"
test_var = "c"
```
and test it passes is 100%:
```gdscript
func  test_variables_in_strings():
	watch_rakugo_signals()

	await wait_parse_and_execute_script(file_path)

	assert_variable("test_var", TYPE_STRING, "c")

	assert_variable("test_var_b", TYPE_STRING, "cb")

	await wait_execute_script_finished(file_base_name)
```

**Comment by Jeremi360** [comment]
@theludovyc do you think I can merge #256 ?

**Comment by theludovyc** [comment]
No, I will make a review when I will be at home. It the meantime you can squash your commits and remove unrelated files 😊

**Comment by Jeremi360** [comment]
@theludovyc What *"unrelated files"* you mean ? 
If your are talking about files in *TestVarsInStrings* dir, then it is alredy removed.

**Comment by theludovyc** [comment]
Review is ready 😊 (maybe next time we can talk all about the technical stuff in the pr and not in the issue 😅)
