### ISSUE TITLE
Lot of character_tag empty warnings !

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#259]
![image](https://github.com/rakugoteam/Rakugo-Dialogue-System/assets/7337158/759a9d7e-19b2-41a0-85ed-d2aaa6c25c08)

Do you want to do something about that or not ?

Because technicaly call get_character with an empty tag is not recomanded...

**Comment by Jeremi360** [comment]
@theludovyc I think we should remove this as when users don't add tag they just want to use narrator - like in Ren'Py Script. Having empty tag dosen't brake anything in RakuScript, so it waring can be only frustrating.
