### ISSUE TITLE
Jump on values where the ! operator returns true in gdscript fails

### ISSUE THREAD

**Issue by Mojken** [rakugoteam/Rakugo-Dialogue-System#273]
Jumping on values such as 0, where in gdscript the `!`-operator makes them return `true` fails in execution with a cryptic error message. This is because of line 154 in Executed.gd, it should probably say `if var_ == null` instead. Really `get_variable` should return a bool value saying if it found anything, or something similar to that.

**To Reproduce**
```
char.var = 0
jump test if char.var == 0

test:
    char "This won't ever happen"
```

**Expected behavior**
You should be able to jump on zero values

**Runtime:**
 - Godot version 4.1.3
 - Rakugo Version 2.2

**Comment by Jeremi360** [comment]
@Mojken Thanks for reporting this bug.
So your are right that `if var_ == null` would be safer.

Also to crate var you can just do `var_name = value`,
I just notice that docs can misslead you that you need to do:
`char.var_name = value` - you can do this but only
if you want varibale attached to already existing character,
to crate character you do `character character_name "Character Name To Display"`.
I will fix docs so they wouldn't be missleading in this way soon also.
