### ISSUE TITLE
Invalid get index 'current_dialogue' (on base: 'Node (Rakugo.gd)').

### ISSUE THREAD

**Issue by MatteoPiovanelli** [rakugoteam/Rakugo-Dialogue-System#38]
https://github.com/rakugoteam/Rakugo/blob/b8de37f2aaa2bb0dd2384cb83d47dbb850c54424/addons/Rakugo/lib/systems/History.gd#L75

https://github.com/rakugoteam/Rakugo/blob/b8de37f2aaa2bb0dd2384cb83d47dbb850c54424/addons/Rakugo/lib/systems/History.gd#L78

Property 'current_dialogue' is still used in these two lines.

**Comment by Jeremi360** [comment]
fixed with #39
