### ISSUE TITLE
Fix jump()

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#4]
I found that ```jump()``` not works as it should,
but it was some time ago, I need to check it again.
And fix this error.

**Comment by theludovyc** [comment]
@Jeremi360 What we do with this ?

**Comment by Jeremi360** [comment]
> @Jeremi360 What we do with this ?

By looking at the date I suppose it about `Rakugo.jump()` and not about `jump` in RakuScript ?
If Yes then just remove `jump()` from Rakugo.

**Comment by theludovyc** [comment]
> By looking at the date I suppose it about `Rakugo.jump()` and not about `jump` in RakuScript ? If Yes then just remove `jump()` from Rakugo.

I think it is. I copy this issue from older project ^^

**Comment by Jeremi360** [comment]
> I think it is. I copy this issue from older project ^^

Then we can close it with no regret, but first we must remove those 2:
- [`Rakugo.jump()`](https://github.com/rakugoteam/Rakugo/blob/05a7a6ecd4254483eeb2c68692412d79f72c391a/addons/Rakugo/Rakugo.gd#L322)
- [*addons/Rakugo/lib/statements/Jump.gd*](https://github.com/rakugoteam/Rakugo/blob/1.0/addons/Rakugo/lib/statements/Jump.gd)
