### ISSUE TITLE
Made ```cond()``` works also with ```match```

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#5]
**Is your feature request related to a problem? Please describe.**
Now, ```cond()``` works only with ```if```.
For some more complicated cases for e.g. ```menu()```
use ```match``` will easier to use.

**Describe the solution you'd like**
It is probably enough for ```cond()``` to return the result of the argument passed to it, without changing it to bool.

**Describe alternatives you've considered**
Made new similar to ```cond()``` method just for use with ```match```.

**Comment by Jeremi360** [comment]
@theludovyc I think no longer relevant as we will have it fixed by `if`s in `gdscript` blocks in RakuScript.
