### ISSUE TITLE
Rakugo not works on itch.io with firefox

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#52]
In readme add section export Html5 to specify below options

![image](https://user-images.githubusercontent.com/7337158/162470941-c30307a3-30a9-4ba0-8908-d7d9c0bde6b8.png)

![image](https://user-images.githubusercontent.com/7337158/162471020-a9ae8269-6a49-4ab7-a960-79333f35f7c6.png)

**Comment by Jeremi360** [comment]
This second option must be specified for any type of export not only web one.

**Comment by theludovyc** [comment]
Please read https://itch.io/post/5713938

**Comment by Jeremi360** [comment]
We should add those Export instructions to wiki/docs

**Comment by theludovyc** [comment]
Yep :)

**Comment by Jeremi360** [comment]
added to docs: https://github.com/rakugoteam/rakugo-docs/pull/3
https://rakugoteam.github.io/rakugo-docs/export/

**Comment by theludovyc** [comment]
Really great news, it works now with Godot 4 !

![image](https://github.com/rakugoteam/Rakugo-Dialogue-System/assets/7337158/09bab87a-e553-49a2-9fea-96a8ad68f840)

I think we can close this issue

**Comment by Jeremi360** [comment]
It's great to hear that, it's good that you remembered to check it out.
I will not close it yet, and what's more, I will add it to milestone 2.1.2 so as not to forget to mettion that it has already been resolved in the news about the 2.1.2 release.
