### ISSUE TITLE
compilation error: var raku_script should probably be file_name 

### ISSUE THREAD

**Issue by MatteoPiovanelli** [rakugoteam/Rakugo-Dialogue-System#54]
https://github.com/rakugoteam/Rakugo/blob/2852b6160455ce712e8066da65752a869153bb4b/addons/Rakugo/lib/nodes/RakuScriptDialogue.gd#L4

**Comment by Jeremi360** [comment]
Why change it when it is only to choose only RakuScript type of file?

**Comment by MatteoPiovanelli** [comment]
sorry, I should have specified better in the issue.
Later in the same file:
https://github.com/rakugoteam/Rakugo/blob/2852b6160455ce712e8066da65752a869153bb4b/addons/Rakugo/lib/nodes/RakuScriptDialogue.gd#L12
causes a compilation error because it's looking for `file_name`

**Comment by Jeremi360** [comment]
Okay I see now, probably merge go wrong, I will fix it soon.
