### ISSUE TITLE
several references to TwitchChat addon

### ISSUE THREAD

**Issue by MatteoPiovanelli** [rakugoteam/Rakugo-Dialogue-System#55]
https://github.com/rakugoteam/Rakugo/blob/2852b6160455ce712e8066da65752a869153bb4b/project.godot#L20

project.godot contains several references to the TwitchChat addon. I think those should be removed? They are removed anyway by the editor on first load of the project, I think

**Comment by Jeremi360** [comment]
This is there because @theludovyc this addon for his streams, 
they should be removed to keep project code clean, 
but is not a big issue, as godot clean it automatically.

**Comment by theludovyc** [comment]
I'm sorry if it's register in projet.godot. I work on this plugin today to reduce this effect :) !

**Comment by theludovyc** [comment]
It's done https://github.com/theludovyc/Godot_Plugin_TwitchChat/releases/tag/v0.3

But I can't delete it there
```
[editor_plugins]
enabled=PoolStringArray( "res://addons/Rakugo/plugin.cfg", "res://addons/TwitchChat/plugin.cfg" )
```

You can close this issue :)

**Comment by theludovyc** [comment]
@Jeremi360 Can you reopen it ? I look project.godot and class_name are in it ^^'

**Comment by Jeremi360** [comment]
> @Jeremi360 Can you reopen it ? I look project.godot and class_name are in it ^^'

Yes.

**Comment by theludovyc** [comment]
You can close it :) !
