### ISSUE TITLE
```cond()``` don't work whit roll back/forward

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#6]
**Describe the bug**
When try to roll in dialogue with ```cond()```
It works, but ```cond()``` result in always false in this case

**To Reproduce**
Steps to reproduce the behaviour:
- Run some Dialogue that has more than 3 steps
- and at least one of them uses ```cond()```
- Go to 3rd or more steps
- Try few times:
- a. Try to rollback
- b. Try rollforward
- See how it behaves

**Expected behavior**
It should roll keeping previous result of passed condition to ```cond()```.

**Runtime (please complete the following information):**
- Godot version 3.4
- Rakugo Version 3.2 RC 1

**Additional context**
Probably ```cond()``` result is not saved/restored when roll

**Comment by Jeremi360** [comment]
@theludovyc I think no longer relevant as we will have it fixed by `if`s in `gdscript` blocks in RakuScript.
