### ISSUE TITLE
Rework Character.gd

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#61]
Don't extends Resource we never use it like that.

Remove visual things like :
- color
- show_parameters
- show
- hide

Remove useless things like :
- say_parameters
- variables
- _get
- _set
- duplicate (it's StoreManager to do it)
- apply_default

Rework :
- get_composite_name (don't return bbcode)

Add :
- Real constructor with _init(...)

Things to now :
- In VnKit we can extends this class to extends possibilities of Character

**Comment by Jeremi360** [comment]
About this removing `variables`, those `variables`  were used for stuff like `emi.relationship`,
but now when we have RakuScript it can be just RakuScript variable.
I remember that (but I can't fund issue about it) that we talk to allow to 
define subvariables for characters in it just by writing `character_id.variable_name = value`

I moved talk about character variables to speared idea: #65
