### ISSUE TITLE
Character variables / Custom Character Resource

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-Dialogue-System#65]
This continuation of this: https://github.com/rakugoteam/Rakugo/issues/61#issuecomment-1116420822
> About this removing variables, those variables were used for stuff like emi.relationship,
but now when we have RakuScript it can be just RakuScript variable.
I remember that (but I can't fund issue about it) that we talk to allow to
define subvariables for characters in it just by writing `character_id.variable_name = value`

So I have 2 ideas about this we can do both and mix them or just one:

1. like proposed above characters can have subvariables defined in RakuScript, 
(I think) it will be easy to add we just need to allow for `.` sine in variable name
and then when parse we check if character with this id exist if not error.
This also can be defined in blocks:
```
# line approuch
character ami "Ami Jones"
ami.relationship = 0

# block approuch
character emi "Emi Jones":
  relationship = 0
  sisters = [ami]

ami.sisters = [emi]
```

2. Second idea that I have is to allow *Custom Character Resource*.
This will work that user creates Resource type that extends our Character Resource.
Then user choose this new script resource as *ProjectSettings > Rakugo/Custom Character Resource*.
After this change, Rakugo parser when character is defined it will use `_init()`  for script selected as *Custom Character Resource*.
And it if it will have some variables, then we can overwrite them from RakuScript.

**Comment by theludovyc** [comment]
I think about it.

I like first one. And I realize in second one, if user extends it, he need to redefine to_dictionary too for save.

When I saw old code, I thinked we can have a dictionary of things called "properties". We can use it to store "variables", "properties" or "texture" for portraits. It's like old one, but better.

**Comment by Jeremi360** [comment]
> I like first one. 

I like it too, a lot.

> And I realize in second one, if user extends it, he need to redefine to_dictionary too for save.

I didn't realize that it will require such change, but it looks for simple change, but now I like first one even more.
 
> When I saw old code, I thinked we can have a dictionary of things called "properties". We can use it to store "variables", "properties" or "texture" for portraits. It's like old one, but better.

It will be simpler than second one to implement and use.

**Comment by Jeremi360** [comment]
is the same as #72
