### ISSUE TITLE
Variables in RakuScript

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-Dialogue-System#66]
We need variables in RakuScript, those will be:
- global
- saved to save file
- used in `if`s
- used in loops

For now, its declaration will look like this:
```python
var_name = value
```
Maybe we need to add `var` keyword to it to make it simpler, as this is the same as overriding an already existing variable.

To get/set to this variable from GDScript you just do:
```gdscript
var rakugo_test_var = Rakugo.get("test_var")

rakugo_test_var.set(100)
```

**Comment by theludovyc** [comment]
You don't review my code 😱 ! Save/Store/Read/Write variable it's already here https://github.com/rakugoteam/Rakugo/blob/973db16a238ba933a6e3b2a61c1b49ccac5d8df9/addons/Rakugo/Rakugo.gd#L78

**Comment by theludovyc** [comment]
So it's works in gdScript, now I need to do it with rakuScript
