### ISSUE TITLE
Clean up Rakugo Core form code and assets that will be now in other plugins

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#7]
⚠️ It will broke Rakugo NV Kit that this repo will become ⚠️ ,
so it must be done on new repo where there is only clean Godot project with Rakugo.

So I partially separated Rakugo to different plugins such as:

- Emojis-For-Godot
- AdvancedText
- Adventrue

And I didn't fully clean up the code that I transferred into these plugins from the Rakugo core.
I think there only left stuff related to AdvancedText :

- RakugoTextLabel node and icon
- TextParser node and icon
- CodeEdit node and icon
- keywords dir
- and also all references in code to them must be removed.

**Comment by Jeremi360** [comment]
all of this stuff is removed
