### ISSUE TITLE
Super Say (Handle variables and characters)

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#72]
Currently say just handle basic string. We can think about make better.

Handle variable and characters can do it like that
```
"I think [character_name] have <age> years old```
```

What do you think ?

**Comment by Jeremi360** [comment]
First way once your example uses `[ ]` next time uses `< >` ?

Second I think we don't have to doing this, as [AdvancedTextLabel](https://github.com/rakugoteam/AdvancedText/blob/1fd38c4c565203500c59bfcc785b9eb63298e321/addons/advanced-text/parsers/EBBCodeParser.gd#L37) already supports this,
the only thing I must change is to add code to get Rakugo variables dictionary if possible.

Third, I think it should be `[character.name]` like I proposed in #65 .

**Comment by theludovyc** [comment]
Use [ ] for variables and <> for characters

**Comment by Jeremi360** [comment]
> Use [ ] for variables and <> for characters

You can elaborate on `<> for characters` I don't get it ?

And what are your answers for those 2:
> Second I think we don't have to doing this, as [AdvancedTextLabel](https://github.com/rakugoteam/AdvancedText/blob/1fd38c4c565203500c59bfcc785b9eb63298e321/addons/advanced-text/parsers/EBBCodeParser.gd#L37) already supports this,
the only thing I must change is to add code to get Rakugo variables dictionary if possible.

> Third, I think it should be [character.name] like I proposed in https://github.com/rakugoteam/Rakugo/issues/65 .

**Comment by theludovyc** [comment]
If we use [ ] and < >, I know if it [ ] it's variable so I use Rakugo.get_variable(). And if it's < > it's character so I use Rakugo.get_character().
With this solution we can have character and variable with same name.

It Rakugo to do this, beacause it know how to do it.

Yes, we can use [character_tag.name]

**Comment by Jeremi360** [comment]
> If we use [ ] and < >, I know if it [ ] it's variable so I use Rakugo.get_variable(). And if it's < > it's character so I use Rakugo.get_character().
With this solution we can have character and variable with same name.

I see, but I think this would be a bit confusing.

> It Rakugo to do this, beacause it know how to do it.
Okay, I see that this would more proper way.

> Yes, we can use [character_tag.name]
😄 

Now #72 doubles this so, I close #72.

**Comment by theludovyc** [comment]
I thought about it. If we never use character_tag alone (but character_tag.var_name), we can only use [ ] or < > for both variables and character's variables.

Exemples
[coins] <= it's a variable

[sy.coins] <= it's a character variable

What do you prefer [ ] or < > ?

**Comment by Jeremi360** [comment]
> I thought about it. If we never use character_tag alone (but character_tag.var_name), 
we can only use [ ] or < > for both variables and character's variables.

Yes,  That's exactly what I had in mind.

> What do you prefer [ ] or < > ?

I prefer `< >` as don't mess up/confuse users, as both bbcode and markdown uses `[ ]` for different things then vars.
And users will be able to use them in strings thanks to AdvancedText - if they want.
And AdvancedText also supports Ren'Py, which normally uses `[ ]` for vars,
but I think it wouldn't be such much of a deal if we just explain in our docs in feature why in your case it is `< >` instead of '[ ]'

**Comment by theludovyc** [comment]
Okay we use <> for variables and characters's variables :)

**Comment by Jeremi360** [comment]
@theludovyc , you called this issues *Super Say* it mean it will only support vars in `say` statement strings ?
I think all string should support it, for example I often saw in Ren'Py vn that you can name each npc as you want,
and then you have often menu asking with witch you should spend time now.

**Comment by theludovyc** [comment]
I think about it too, it can be usefull in menu choices too, but time by time :)

**Comment by Jeremi360** [comment]
> I think about it too, it can be usefull in menu choices too, but time by time :)

I see it is good to take things step by step.

**Comment by theludovyc** [comment]
Yeah, sometimes I don't explode everything and I do this with finesse :p
