### ISSUE TITLE
Jump label_name if ...

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#81]
Before to do #33

"jump label_name if" is easier to make than if/elif/else statement

We can program like in https://store.steampowered.com/app/375820/Human_Resource_Machine/

So we will can make a new really functionnal and usuable release of RakugoCore after doing this :) ! (and some stuff like #72 and #61 )

**Comment by Jeremi360** [comment]
> "jump label_name if" is easier to make than if/elif/else statement

I read it first without context as it is the most conspicuous line of text,
and got a little scared, because it sounded like an ordinary `if` would not be at all.

Then maybe to make it a bit easier, we can have `call` like in Ren'Py ?
`call` like in Ren'Py calls a dialogue almost like a function, 
and after it is done go back to dialogue it was called from.
https://www.renpy.org/doc/html/label.html#call-statement

**Comment by theludovyc** [comment]
> I read it first without context as it is the most conspicuous line of text, and got a little scared, because it sounded like an ordinary `if` would not be at all.

You really need to play or look at it [human resource](https://store.steampowered.com/app/375820/Human_Resource_Machine/)
It sounded like an ordinary If but it's not.

> Then maybe to make it a bit easier, we can have `call` like in Ren'Py ? `call` like in Ren'Py calls a dialogue almost like a function, and after it is done go back to dialogue it was called from. https://www.renpy.org/doc/html/label.html#call-statement

Not same like jump at all. And we need to update architecture a lot to do this. Plus explain how it works to people. Maybe they don't have a great level in programmation. Gonna be hard.

**Comment by Jeremi360** [comment]
> You really need to play or look at it human resource

I started played it recently.

> It sounded like an ordinary `If` but it's not.

I understand it is not, I just as I saw this line at first and misinterpreted it at that moment.

> Not same like jump at all. And we need to update architecture a lot to do this. Plus explain how it works to people. Maybe they don't have a great level in programmation. Gonna be hard.

Okay, you are probably right, I did not think it through, 
just this idea came to my mind, I wanted to give it to consideration.

**Comment by theludovyc** [comment]
> I started played it recently.

Yeah 🥳 

> Okay, you are probably right, I did not think it through, just this idea came to my mind, I wanted to give it to consideration.

I am agree with you #82 😊

**Comment by theludovyc** [comment]
Need #72 to replace variables in if :)

**Comment by theludovyc** [comment]
Handle variables o/

![image](https://user-images.githubusercontent.com/7337158/172054289-28f728c0-0d94-4061-a674-4e527914e753.png)

Time to characters's variables ^^

**Comment by theludovyc** [comment]
I use godot's expression class https://github.com/theludovyc/Rakugo/blob/3d1d7ba4cabf3b8c18228fdf5e6dd633acc7959e/addons/Rakugo/lib/systems/Parser.gd#L238

It does not like char_name.var_name, because of '.'

I need to replace char_name.var_name by char_name_var_name in string expression before use

**Comment by theludovyc** [comment]
do #95 before :)
