### ISSUE TITLE
StoreManager, save position (reading line) in rk script

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#88]
Create a func in storemanager and rakugo, to save rk script position

**Comment by theludovyc** [comment]
Do #84 before :)

**Comment by theludovyc** [comment]
Do #124 before :)

**Comment by theludovyc** [comment]
@Jeremi360 Imagine we have saved the name of last script have run and the number of last line it read. We close the game and restart it. When a user do Rakugo.load_game(...), do you want it execute last script from line where it was ? Or do other thing ?

**Comment by Jeremi360** [comment]
> Imagine we have saved the name of last script have run and the number of last line it read. We close the game and restart it. When a user do Rakugo.load_game(...), do you want it execute last script from line where it was ? Or do other thing ?

So yes, at first I thought that getting the script from the last line where it ended is not enough, 
because we also need to somehow restore the state of the scene from the moment of save.
But as I thought about it, I understood that there is no such need.
Simply put, adding signal `game_loaded` will enough and  
this way the user will load what he needs from` Rakugo.variables` and apply it on scene, e.g. player position.

**Comment by theludovyc** [comment]
I create new issue for it #187 

So to be sure, when Rakugo.load_game, it parse last script have run and start at last line it read ?

**Comment by Jeremi360** [comment]
> So to be sure, when Rakugo.load_game, it parse last script have run and start at last line it read ?

Yes.

**Comment by theludovyc** [comment]
After consideration, I split it in 2 func. One for load and parse last script. And second to start script. In this case you can call load, to have access to rakugo vars. Then load your scene with background, characters sheets, sounds, etc... And finaly call Rakugo.execute_last_script(). I am afraid if we do it in one func, we send say signal (by example) to early.

I need your help to search a name for Rakugo.execute_last_script(). I think is not enough explicit. Maybe Rakugo.execute_last_script_after_load() ? What do you think ?

**Comment by Jeremi360** [comment]
> After consideration, I split it in 2 func. One for load and parse last script. And second to start script. In this case you can call load, to have access to rakugo vars. Then load your scene with background, characters sheets, sounds, etc... And finaly call Rakugo.execute_last_script(). I am afraid if we do it in one func, we send say signal (by example) to early.

I also think that spliting them is a good idea.

> I need your help to search a name for Rakugo.execute_last_script(). I think is not enough explicit. Maybe Rakugo.execute_last_script_after_load() ? What do you think ?

I think we can call it `Rakugo.resume_last_script()` ?

**Comment by theludovyc** [comment]
Resume is a great idea ! What do you think about Rakugo.resume_loaded_script() ?

**Comment by Jeremi360** [comment]
> Resume is a great idea ! What do you think about Rakugo.resume_loaded_script() ?

Yes, this sound good,
