### ISSUE TITLE
Parser, variable's name can't be one letter long

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#93]
Current regex to check valid variable name
```
VALID_VARIABLE = "[a-zA-Z_][a-zA-Z_0-9]+"
```

So we can't do
```
a = 5
```

**Comment by Jeremi360** [comment]
I look at cheatsheet at https://regexr.com and there is that:
 `a*` is  0 or more, so we need just change this regex to:
`VALID_VARIABLE = "[a-zA-Z_][a-zA-Z_0-9]*"`

**Comment by theludovyc** [comment]
Regex `VALID_VARIABLE = "[a-zA-Z_][a-zA-Z_0-9]*"` can match something like `_ = 5`

**Comment by theludovyc** [comment]
Maybe we can say variable don't start by a '_' ?

**Comment by Jeremi360** [comment]
> Maybe we can say variable don't start by a '_' ?
Yes this is a good idea in our case, 
normally I would be against the name of variables not starting with `_`, 
because this is how private in programming languages are used to be, 
but in the case of Rkscript there is no private speech or need, so we can easily do it.
