### ISSUE TITLE
Rakugo, set_variable, get_variable, can handle character's variable

### ISSUE THREAD

**Issue by theludovyc** [rakugoteam/Rakugo-Dialogue-System#95]
By exemple
```gdscript
Rakugo.get_variable("sy.name")
```

Make things easier for Parser, instead of check character's variable, and next variable, we can do this at same time.

And it shorter func name like you want in https://github.com/rakugoteam/Rakugo/pull/83#issuecomment-1135503905 :)

**Comment by Jeremi360** [comment]
> Make things easier for Parser, instead of check character's variable, and next variable, we can do this at same time.
And it shorter func name like you want in https://github.com/rakugoteam/Rakugo/pull/83#issuecomment-1135503905 :)

Great to hear that :smiley:
